"""empty message

Revision ID: 146277236474
Revises: 493fa7b68b94
Create Date: 2021-03-05 10:05:45.283955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146277236474'
down_revision = '493fa7b68b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'vintners', 'areas', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vintners', type_='foreignkey')
    # ### end Alembic commands ###
